export const kelas = {
  data: [
    {
      id: 1,
      nama: "X 4",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
    {
      id: 2,
      nama: "IX 4",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
    {
      id: 4,
      nama: "X 1",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
    {
      id: 1,
      nama: "X 4",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
    {
      id: 2,
      nama: "IX 4",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
    {
      id: 4,
      nama: "X 1",
      jumlahSiswa: 0,
      tahunAjaran: "2022/2023",
      status: "aktif",
    },
  ],
  pageInfo: {
    totalData: 6,
    currentPage: 1,
    lastPage: 1,
    limit: 10,
    nextPage: null,
    prevPage: null,
  },
};

export const siswa = {
  data: [
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
    {
      nis: "123456789098",
      nama: "Ayu Mairoza",
      kelas: "X 4",
      jenis_kelamin: "Perempuan",
      nama_ayah: "Andika Perkara",
      nama_ibu: "Putri Alam Sari",
      alamat: "Bandung",
    },
  ],
  pageInfo: {
    totalData: 3,
    currentPage: 1,
    lastPage: 1,
    limit: 5,
    nextPage: null,
    prevPage: null,
  },
};
